[
    {
      "_id": "66c6e75be722b9191cb1891b",
      "Nombre del producto": "Aceite de oliva",
      "Proveedor": "La Vaquita",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "ml",
      "COSTO": 32990,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-01",
      "STOCK": "NaN",
      "PENDIENTE": "25%",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1891c",
      "Nombre del producto": "Arepa",
      "Proveedor": "Exito",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 10,
      "UNIDADES": "un",
      "COSTO": 7500,
      "COOR": "1.10",
      "FECHA_ACT": "2023-12-10",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1891e",
      "Nombre del producto": "Ajo",
      "Proveedor": "La Vaquita",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 270,
      "UNIDADES": "gr",
      "COSTO": 1900,
      "COOR": 1.05,
      "FECHA_ACT": "2023-04-01",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18923",
      "Nombre del producto": "Azucar Papeleta",
      "Proveedor": "Mundo Huevo",
      "Estado": "75%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 200,
      "UNIDADES": "NaN",
      "COSTO": 6500,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-02",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18926",
      "Nombre del producto": "Berenjena",
      "Proveedor": "La Vaquita",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 1800,
      "COOR": 1.05,
      "FECHA_ACT": "2023-04-01",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18930",
      "Nombre del producto": "Chocolate cobertura",
      "Proveedor": "Mundo Huevo",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 45100,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-01",
      "STOCK": "NaN",
      "GRUPO": "CONDIMENTO_ESPECIA",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18931",
      "Nombre del producto": "Chocolate Salsa",
      "Proveedor": "Mundo Huevo",
      "Estado": "0%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 350,
      "UNIDADES": "gr",
      "COSTO": "15000",
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-02",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": "Corona"
    },
    {
      "_id": "66c6e75be722b9191cb18934",
      "Nombre del producto": "Chorizo español",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 16,
      "UNIDADES": "un",
      "COSTO": 7800,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18940",
      "Nombre del producto": "Garbanzo",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 4800,
      "COOR": 1.05,
      "FECHA_ACT": "2023-04-03",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18949",
      "Nombre del producto": "Limon",
      "Proveedor": "La Vaquita",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 3500,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-09",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1894c",
      "Nombre del producto": "Leche Condenzada",
      "Proveedor": "La Vaquita",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 900,
      "UNIDADES": "ml",
      "COSTO": 2950,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-09",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1894e",
      "Nombre del producto": "Licor - Vino de Café",
      "Proveedor": "Mandalas",
      "Estado": "50%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 400,
      "UNIDADES": "NaN",
      "COSTO": 20000,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-10",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1894f",
      "Nombre del producto": "Maracuya",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 319,
      "UNIDADES": "gr",
      "COSTO": 4000,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-11",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18952",
      "Nombre del producto": "Milo",
      "Proveedor": "PriceSmart",
      "Estado": "50%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 750,
      "UNIDADES": "gr",
      "COSTO": 30900,
      "COOR": 1.05,
      "FECHA_ACT": "2024-01-22",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18956",
      "Nombre del producto": "Nuez Mozcada",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 85,
      "UNIDADES": "gr",
      "COSTO": 4050,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "CONDIMENTO_ESPECIA",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18920",
      "Nombre del producto": "Arandanos Azules",
      "Proveedor": "Mundo Huevo",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 38000,
      "COOR": 1.05,
      "FECHA_ACT": "2023-12-10",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18925",
      "Nombre del producto": "Arepa Mote Exito",
      "Proveedor": "NaN",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 5,
      "UNIDADES": "un",
      "COSTO": 2800,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1892e",
      "Nombre del producto": "Canela Molida Tarro ",
      "Proveedor": "La Vaquita",
      "Estado": "50%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 14,
      "UNIDADES": "gr",
      "COSTO": 6000,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-02",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18933",
      "Nombre del producto": "Chorizo campesino",
      "Proveedor": "Exito",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 12,
      "UNIDADES": "un",
      "COSTO": 12000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18935",
      "Nombre del producto": "Crema de Leche Alpina Maxilitro",
      "Proveedor": "La Vaquita",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1100,
      "UNIDADES": "ml",
      "COSTO": 21450,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-02",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18938",
      "Nombre del producto": "Crema de Queso",
      "Proveedor": "Dulces Tonterias",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 38000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18946",
      "Nombre del producto": "Jamon Sanduche",
      "Proveedor": "Mundo Huevo",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 24,
      "UNIDADES": "un",
      "COSTO": 12100,
      "COOR": 1.05,
      "FECHA_ACT": "2023-12-10",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1894b",
      "Nombre del producto": "Leche deslactozada",
      "Proveedor": "La Vaquita",
      "Estado": "25%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 900,
      "UNIDADES": "ml",
      "COSTO": 2950,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-09",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18950",
      "Nombre del producto": "Manzana Verde",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1360,
      "UNIDADES": "gr",
      "COSTO": 15900,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-09",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1891d",
      "Nombre del producto": "Aceite vegetal de soya",
      "Proveedor": "La Vaquita",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 2700,
      "UNIDADES": "ml",
      "COSTO": 23990,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-01",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18922",
      "Nombre del producto": "Azucar morena",
      "Proveedor": "Mundo Huevo",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 4850,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-01",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18924",
      "Nombre del producto": "Aguacate",
      "Proveedor": "Carreta",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 4,
      "UNIDADES": "srv",
      "COSTO": 5000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18927",
      "Nombre del producto": "Bicarbonato de sodio",
      "Proveedor": "La Vaquita",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 7250,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-01",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18928",
      "Nombre del producto": "Banano",
      "Proveedor": "Carreta",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 14,
      "UNIDADES": "un",
      "COSTO": 8000,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-02",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1892a",
      "Nombre del producto": "Caldo deshidratado",
      "Proveedor": "La Vaquita",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "ml",
      "COSTO": 4450,
      "COOR": 1.05,
      "FECHA_ACT": "2023-04-01",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1892b",
      "Nombre del producto": "Lata tomates pelados",
      "Proveedor": "PriceSmart",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 2890,
      "UNIDADES": "gr",
      "COSTO": 24900,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1892c",
      "Nombre del producto": "Cebolla roja",
      "Proveedor": "La Vaquita",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 2250,
      "COOR": 1.05,
      "FECHA_ACT": "2023-04-01",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1892d",
      "Nombre del producto": "Cebolla blanca",
      "Proveedor": "La Vaquita",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 3500,
      "COOR": 1.05,
      "FECHA_ACT": "2023-12-11",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18936",
      "Nombre del producto": "Crema Chantilli",
      "Proveedor": "Mundo Huevo",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 250,
      "UNIDADES": "gr",
      "COSTO": 18500,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1893b",
      "Nombre del producto": "Esencia vainilla",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 60,
      "UNIDADES": "NaN",
      "COSTO": 3800,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-03",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1893d",
      "Nombre del producto": "Fecula maiz (maizena)",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 720,
      "UNIDADES": "gr",
      "COSTO": 20690,
      "COOR": 1.05,
      "FECHA_ACT": "2023-04-02",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1893e",
      "Nombre del producto": "Fresas",
      "Proveedor": "Carreta",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 8000,
      "COOR": 1.05,
      "FECHA_ACT": "2023-04-03",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1893f",
      "Nombre del producto": "Granola",
      "Proveedor": "ADHER",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 950,
      "UNIDADES": "gr",
      "COSTO": 12350,
      "COOR": 1.05,
      "FECHA_ACT": "2023-01-02",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18945",
      "Nombre del producto": "Hielo",
      "Proveedor": "Frescampo",
      "Estado": "0%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 3000,
      "UNIDADES": "gr",
      "COSTO": 6000,
      "COOR": 1.05,
      "FECHA_ACT": "2024-01-17",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1894d",
      "Nombre del producto": "Leche en polvo",
      "Proveedor": "Colanta",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 380,
      "UNIDADES": "gr",
      "COSTO": 15400,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18951",
      "Nombre del producto": "Mantequilla",
      "Proveedor": "NaN",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 15900,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-09",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18954",
      "Nombre del producto": "Nachos",
      "Proveedor": "Mundo Huevo",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 12650,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18957",
      "Nombre del producto": "Parmegiano",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 453,
      "UNIDADES": "gr",
      "COSTO": 35000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18958",
      "Nombre del producto": "Pasta de tomate",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 200,
      "UNIDADES": "gr",
      "COSTO": 6350,
      "COOR": 1.05,
      "FECHA_ACT": "2023-04-01",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1891f",
      "Nombre del producto": "Apio",
      "Proveedor": "La Vaquita",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1200,
      "UNIDADES": "gr",
      "COSTO": 950,
      "COOR": 1.05,
      "FECHA_ACT": "2023-04-01",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18921",
      "Nombre del producto": "Azucar blanca",
      "Proveedor": "Mundo Huevo",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 4850,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-01",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18929",
      "Nombre del producto": "Crema agria",
      "Proveedor": "La Vaquita",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 400,
      "UNIDADES": "gr",
      "COSTO": 10950,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1892f",
      "Nombre del producto": "Chocolate ( Cocoa en polvo)",
      "Proveedor": "Mundo Huevo",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 36300,
      "COOR": 1.05,
      "FECHA_ACT": "2023-08-31",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18932",
      "Nombre del producto": "Chimichurri",
      "Proveedor": "Exito",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 227,
      "UNIDADES": "gr",
      "COSTO": 22000,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-02",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18937",
      "Nombre del producto": "Crema Chintilli",
      "Proveedor": "PriceSmart",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 43,
      "UNIDADES": "srv",
      "COSTO": 21900,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18939",
      "Nombre del producto": "Coriandro semilla",
      "Proveedor": "Frutos & Semillas",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 125,
      "UNIDADES": "gr",
      "COSTO": 7100,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1893a",
      "Nombre del producto": "Comino Semilla",
      "Proveedor": "Frutos & Semillas",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 125,
      "UNIDADES": "gr",
      "COSTO": 12100,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1893c",
      "Nombre del producto": "Espinaca",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 30,
      "UNIDADES": "gr",
      "COSTO": 1600,
      "COOR": 1.05,
      "FECHA_ACT": "2023-04-01",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18941",
      "Nombre del producto": "Huevo",
      "Proveedor": "Mundo Huevo",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 30,
      "UNIDADES": "un",
      "COSTO": 17100,
      "COOR": 1.05,
      "FECHA_ACT": "2023-12-10",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18942",
      "Nombre del producto": "Harina de trigo Multiproposito",
      "Proveedor": "Mundo Huevo",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 2500,
      "UNIDADES": "gr",
      "COSTO": 11950,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-09",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18943",
      "Nombre del producto": "Harina de trigo (Fortificada)",
      "Proveedor": "Mundo Huevo",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 2200,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-09",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18944",
      "Nombre del producto": "Hojaldre",
      "Proveedor": "Mundo Huevo",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 15000,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-10",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18947",
      "Nombre del producto": "Jamon Cerrano",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 80,
      "UNIDADES": "gr",
      "COSTO": 6000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18948",
      "Nombre del producto": "Leche entera",
      "Proveedor": "La Vaquita",
      "Estado": "25%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 900,
      "UNIDADES": "ml",
      "COSTO": "2830",
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-09",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1894a",
      "Nombre del producto": "Lenteja",
      "Proveedor": "La Vaquita",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 3600,
      "COOR": 1.05,
      "FECHA_ACT": "2023-04-03",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18953",
      "Nombre del producto": "Sirope de Naple",
      "Proveedor": "Mundo Huevo",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 480,
      "UNIDADES": "ml",
      "COSTO": 9250,
      "COOR": 1.05,
      "FECHA_ACT": "2024-01-22",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18955",
      "Nombre del producto": "Nuces brasil",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 200,
      "UNIDADES": "gr",
      "COSTO": 9750,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1895e",
      "Nombre del producto": "Pimienta Negra",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 70,
      "UNIDADES": "gr",
      "COSTO": 12000,
      "COOR": 1.05,
      "FECHA_ACT": "2023-12-10",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18959",
      "Nombre del producto": "Pasta plana",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 250,
      "UNIDADES": "gr",
      "COSTO": 4950,
      "COOR": 1.05,
      "FECHA_ACT": "2023-04-02",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18963",
      "Nombre del producto": "Queso azul",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 55000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18964",
      "Nombre del producto": "Quesito",
      "Proveedor": "La Vaquita",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 480,
      "UNIDADES": "gr",
      "COSTO": 8390,
      "COOR": 1.05,
      "FECHA_ACT": "2023-12-10",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18968",
      "Nombre del producto": "Queso Crema",
      "Proveedor": "Mundo Huevo",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 380,
      "UNIDADES": "gr",
      "COSTO": 7750,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18976",
      "Nombre del producto": "Tomillo",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 20,
      "UNIDADES": "gr",
      "COSTO": 1490,
      "COOR": 1.05,
      "FECHA_ACT": "2023-10-12",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1897b",
      "Nombre del producto": "Reducción de balsamico",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 250,
      "UNIDADES": "gr",
      "COSTO": "NaN",
      "COOR": "NaN",
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1897c",
      "Nombre del producto": "Yogurt Griego",
      "Proveedor": "NaN",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 29400,
      "COOR": 1.05,
      "FECHA_ACT": "2023-12-10",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1897f",
      "Nombre del producto": "YEAST DRY",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 80,
      "UNIDADES": "gr",
      "COSTO": 8100,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-09",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18981",
      "Nombre del producto": "Pan Masa Madre Molde",
      "Proveedor": "Modou",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 16000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18982",
      "Nombre del producto": "Panela Pulverizada",
      "Proveedor": "Exito",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 6000,
      "COOR": 1.05,
      "FECHA_ACT": "2024-01-17",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1898a",
      "Nombre del producto": "SAL - MESA",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 3000,
      "COOR": 1.05,
      "FECHA_ACT": "2023-04-01",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1898b",
      "Nombre del producto": "SAL - COCINA",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 465,
      "UNIDADES": "NaN",
      "COSTO": 4000,
      "COOR": 1.05,
      "FECHA_ACT": "2023-04-02",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1898c",
      "Nombre del producto": "Flor de jamaica",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 25,
      "UNIDADES": "gr",
      "COSTO": 6760,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18992",
      "Nombre del producto": "Mango TOMMY",
      "Proveedor": "La Vaquita",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 400,
      "UNIDADES": "gr",
      "COSTO": 2560,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18993",
      "Nombre del producto": "Lulo",
      "Proveedor": "La Vaquita",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 8400,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18998",
      "Nombre del producto": "CAFE VEGA",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 2500,
      "UNIDADES": "gr",
      "COSTO": "100000",
      "COOR": "1.05",
      "FECHA_ACT": "23-08-24",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1895b",
      "Nombre del producto": "Pasas",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 200,
      "UNIDADES": "gr",
      "COSTO": 3550,
      "COOR": 1.05,
      "FECHA_ACT": "2023-04-04",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1895a",
      "Nombre del producto": "Polvo de hornear",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 100,
      "UNIDADES": "gr",
      "COSTO": 8500,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-09",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18961",
      "Nombre del producto": "Queso Parmesano",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 453,
      "UNIDADES": "gr",
      "COSTO": 38000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1896d",
      "Nombre del producto": "Carnes",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18977",
      "Nombre del producto": "Te Negro Helado",
      "Proveedor": "Exito",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 600,
      "UNIDADES": "gr",
      "COSTO": 21100,
      "COOR": 1.05,
      "FECHA_ACT": "2024-01-22",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1897a",
      "Nombre del producto": "Rugula",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 250,
      "UNIDADES": "gr",
      "COSTO": 24000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1897e",
      "Nombre del producto": "yeast frash",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 5600,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-09",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18983",
      "Nombre del producto": "Panela",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 4000,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-09",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18984",
      "Nombre del producto": "Pesto",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 190,
      "UNIDADES": "gr",
      "COSTO": 19900,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18987",
      "Nombre del producto": "Semillas de chia",
      "Proveedor": "la Vaquita",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 100,
      "UNIDADES": "gr",
      "COSTO": 5110,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-10",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18988",
      "Nombre del producto": "Splenda",
      "Proveedor": "Splenda",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "un",
      "COSTO": 97700,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-10",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18989",
      "Nombre del producto": "Moras",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 4500,
      "COOR": 1.1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1898f",
      "Nombre del producto": "Leche condenzada",
      "Proveedor": "D1",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 320,
      "UNIDADES": "gr",
      "COSTO": 8750,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1895d",
      "Nombre del producto": "Peperoni",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 14650,
      "COOR": 1.05,
      "FECHA_ACT": "2023-12-10",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18962",
      "Nombre del producto": "Queso Holandes",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 250,
      "UNIDADES": "gr",
      "COSTO": 25000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18967",
      "Nombre del producto": "Queso Tajado Mozeralla",
      "Proveedor": "La Vaquita",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 400,
      "UNIDADES": "gr",
      "COSTO": 9950,
      "COOR": 1.05,
      "FECHA_ACT": "2023-10-12",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1896a",
      "Nombre del producto": "Vino blanco",
      "Proveedor": "La Vaquita",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 750,
      "UNIDADES": "ml",
      "COSTO": 14950,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-09",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1896e",
      "Nombre del producto": "Morrillo de res",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 13950,
      "COOR": 1.05,
      "FECHA_ACT": "2023-04-01",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18970",
      "Nombre del producto": "Misuna Morada",
      "Proveedor": "Principe Conejo",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 12500,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18972",
      "Nombre del producto": "Tocineta de cerdo basico",
      "Proveedor": "Mundo Huevo",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18975",
      "Nombre del producto": "Tomate Uvalina",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 10580,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18978",
      "Nombre del producto": "Carne de cerdo",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 11400,
      "COOR": 1.05,
      "FECHA_ACT": "2023-04-01",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18979",
      "Nombre del producto": "Ron caldas",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 750,
      "UNIDADES": "ml",
      "COSTO": 48800,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-09",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1897d",
      "Nombre del producto": "Yucarina",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18980",
      "Nombre del producto": "Pan Ciabata",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 12,
      "UNIDADES": "un",
      "COSTO": 40800,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18985",
      "Nombre del producto": "Pollo Pechuga Fileteada",
      "Proveedor": "McPollo",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 105,
      "UNIDADES": "gr",
      "COSTO": 3200,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18986",
      "Nombre del producto": "Helado",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 4000,
      "UNIDADES": "NaN",
      "COSTO": 86000,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-09",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1898d",
      "Nombre del producto": "Champiñones",
      "Proveedor": "Éxito",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 250,
      "UNIDADES": "gr",
      "COSTO": 8800,
      "COOR": 1.05,
      "FECHA_ACT": "15/06/2024",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1898e",
      "Nombre del producto": "caja",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1,
      "UNIDADES": "un",
      "COSTO": 1000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18990",
      "Nombre del producto": "aceitunas negras",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 340,
      "UNIDADES": "gr",
      "COSTO": 17300,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18995",
      "Nombre del producto": "Arroz Blanco Crudo",
      "Proveedor": "La Vaquita",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 2500,
      "UNIDADES": "gr",
      "COSTO": 10900,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1895c",
      "Nombre del producto": "Pechuga",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 11900,
      "COOR": 1.05,
      "FECHA_ACT": "2024-04-26",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1895f",
      "Nombre del producto": "Papa Capira",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 3000,
      "UNIDADES": "gr",
      "COSTO": 16000,
      "COOR": 1.05,
      "FECHA_ACT": "15/6/2024",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18960",
      "Nombre del producto": "Pimenton",
      "Proveedor": "Exito",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 5500,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18965",
      "Nombre del producto": "Queso costeño",
      "Proveedor": "Mundo Huevo",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18966",
      "Nombre del producto": "Queso feta",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 680,
      "UNIDADES": "gr",
      "COSTO": 41900,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18969",
      "Nombre del producto": "Vinagre de manzana",
      "Proveedor": "La Vaquita",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "ml",
      "COSTO": 13550,
      "COOR": 1.05,
      "FECHA_ACT": "2023-09-09",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1896b",
      "Nombre del producto": "Vinagre balsamico",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 250,
      "UNIDADES": "ml",
      "COSTO": 10000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1896c",
      "Nombre del producto": "Zanahoria",
      "Proveedor": "La Vaquita",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 2140,
      "COOR": 1.05,
      "FECHA_ACT": "15/06/2024",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1896f",
      "Nombre del producto": "Mozarrella de bufala",
      "Proveedor": "Mundo Huevo",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 250,
      "UNIDADES": "gr",
      "COSTO": 10700,
      "COOR": 1.05,
      "FECHA_ACT": "2023-12-10",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18971",
      "Nombre del producto": "Tocineta de cerdo Ahumado",
      "Proveedor": "Mundo Huevo",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "un",
      "COSTO": 25850,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18973",
      "Nombre del producto": "Tomate Chonto",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 6000,
      "COOR": 1.05,
      "FECHA_ACT": "2023-10-12",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18974",
      "Nombre del producto": "Tomate Enlatado",
      "Proveedor": "PriceSmart",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 2900,
      "UNIDADES": "gr",
      "COSTO": 37900,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18991",
      "Nombre del producto": "Pepino",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "gr",
      "COSTO": 940,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18994",
      "Nombre del producto": "Piña Oro miel",
      "Proveedor": "La Vaquita",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 2000,
      "UNIDADES": "gr",
      "COSTO": 9800,
      "COOR": 1.6,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18996",
      "Nombre del producto": "Yuca",
      "Proveedor": "La Vaquita",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 2300,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1899c",
      "Nombre del producto": "SODA",
      "Proveedor": "BRETAÑA 300ml",
      "Estado": "25%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 12,
      "UNIDADES": "un",
      "COSTO": 26000,
      "COOR": 1.1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1899a",
      "Nombre del producto": "CAFE LIOFILIZADO",
      "Proveedor": "JUAN VALDEZ",
      "Estado": "0%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 95,
      "UNIDADES": "gr",
      "COSTO": 12000,
      "COOR": 1.1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1899e",
      "Nombre del producto": "Mandarina DesHidratada",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 80,
      "UNIDADES": "gr",
      "COSTO": 10000,
      "COOR": 1.1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189ab",
      "Nombre del producto": "Papel Aluminio",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 100,
      "UNIDADES": "NaN",
      "COSTO": 30000,
      "COOR": 1.1,
      "FECHA_ACT": "2023-11",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189b1",
      "Nombre del producto": "Jugo de Limon",
      "Proveedor": "TREE FRUTS",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 250,
      "UNIDADES": "ml",
      "COSTO": 3000,
      "COOR": 1.1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189bb",
      "Nombre del producto": "Kombucha per te",
      "Proveedor": "Lina Gil",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "ml",
      "COSTO": 23000,
      "COOR": 1.05,
      "FECHA_ACT": "21/06/24",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189c1",
      "Nombre del producto": "TABLA",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 27000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189c4",
      "Nombre del producto": "PIERNA ECONOMICA",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 16000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189ce",
      "Nombre del producto": "Salsa Shakshukas",
      "Proveedor": "INTERNO",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "produccion_interna",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "NaN",
      "COSTO": 35533.21,
      "COOR": 1,
      "FECHA_ACT": "2024-08-04",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189d8",
      "Nombre del producto": "SIROPE DE VAINILLA",
      "Proveedor": "INTERNO",
      "Estado": "100%",
      "Area": "CAFE_BEBIDAS",
      "category": "produccion_interna",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "NaN",
      "COSTO": 9618.13,
      "COOR": 1,
      "FECHA_ACT": "2024-08-04",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1899f",
      "Nombre del producto": "Romero",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 50,
      "UNIDADES": "gr",
      "COSTO": 4170,
      "COOR": 1.1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189a0",
      "Nombre del producto": "Filtro de papel",
      "Proveedor": "NaN",
      "Estado": "100%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "un",
      "COSTO": 40000,
      "COOR": 1.1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189a2",
      "Nombre del producto": "Servilleta Nube Disp x 100",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 4,
      "UNIDADES": "NaN",
      "COSTO": 6723,
      "COOR": 1.1,
      "FECHA_ACT": "2023-11",
      "STOCK": 18.48825,
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189a3",
      "Nombre del producto": "Bowl 32 oz",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 50,
      "UNIDADES": "un",
      "COSTO": 29370,
      "COOR": 1.1,
      "FECHA_ACT": "2023-11",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189a7",
      "Nombre del producto": "Pitillo Caña de Azucar",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 200,
      "UNIDADES": "un",
      "COSTO": 13109,
      "COOR": 1.1,
      "FECHA_ACT": "2023-11",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189aa",
      "Nombre del producto": "Portavasos K/K 2 PUEST",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 15,
      "UNIDADES": "un",
      "COSTO": 6555,
      "COOR": 1.1,
      "FECHA_ACT": "2023-11",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189b0",
      "Nombre del producto": "Jugo de naranja",
      "Proveedor": "TREE FRUTS",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "ml",
      "COSTO": 6000,
      "COOR": 1.1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189b3",
      "Nombre del producto": "PanMolde",
      "Proveedor": "Fermentados",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 18,
      "UNIDADES": "un",
      "COSTO": 25000,
      "COOR": 1.1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189b5",
      "Nombre del producto": "Carne de hamburguesa",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": "NaN",
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189b6",
      "Nombre del producto": "Queso parmesano",
      "Proveedor": "Exitp",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 250,
      "UNIDADES": "gr",
      "COSTO": 20200,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189b9",
      "Nombre del producto": "Vino Tinto",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 750,
      "UNIDADES": "gr",
      "COSTO": 74800,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189bc",
      "Nombre del producto": "Aromatica",
      "Proveedor": "NaN",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 20,
      "UNIDADES": "un",
      "COSTO": 9000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189bd",
      "Nombre del producto": "Bebida de almendras",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 5676,
      "UNIDADES": "ml",
      "COSTO": 62500,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189be",
      "Nombre del producto": "PROMEDIO DE FRUTAS",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": "NaN",
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189c7",
      "Nombre del producto": "LAGARTO",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 21000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189ca",
      "Nombre del producto": "Anis estrellado",
      "Proveedor": "La Vaquita",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 20,
      "UNIDADES": "gr",
      "COSTO": 3190,
      "COOR": 1.05,
      "FECHA_ACT": "2024-07-08",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189cf",
      "Nombre del producto": "Yogurt Griego",
      "Proveedor": "INTERNO",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "produccion_interna",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "NaN",
      "COSTO": 24444.24,
      "COOR": 1,
      "FECHA_ACT": "2024-08-04",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189db",
      "Nombre del producto": "COLD BREW BASE",
      "Proveedor": "INTERNO",
      "Estado": "100%",
      "Area": "CAFE_BEBIDAS",
      "category": "produccion_interna",
      "type": "items",
      "CANTIDAD": 1500,
      "UNIDADES": "NaN",
      "COSTO": 9859.58,
      "COOR": 1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb18999",
      "Nombre del producto": "CAFE LUCUS",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 2500,
      "UNIDADES": "gr",
      "COSTO": 140000,
      "COOR": "1.05",
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1899d",
      "Nombre del producto": "Naranja DesHidratada",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 80,
      "UNIDADES": "gr",
      "COSTO": 10000,
      "COOR": 1.1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189a4",
      "Nombre del producto": "Tapa Bowl 32oz",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 50,
      "UNIDADES": "un",
      "COSTO": 21765,
      "COOR": 1.1,
      "FECHA_ACT": "2023-11",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189a5",
      "Nombre del producto": "Vaso WAU 12oz trasluc",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 50,
      "UNIDADES": "un",
      "COSTO": 14370,
      "COOR": 1.1,
      "FECHA_ACT": "2023-11",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189a6",
      "Nombre del producto": "Tapa Domo Perf",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 50,
      "UNIDADES": "un",
      "COSTO": 10378,
      "COOR": 1.1,
      "FECHA_ACT": "2023-11",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189a8",
      "Nombre del producto": "Vaso 7 oz papel",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 50,
      "UNIDADES": "un",
      "COSTO": 8740,
      "COOR": 1.1,
      "FECHA_ACT": "2023-11",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189a9",
      "Nombre del producto": "Tapa Blanca 7oz",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 50,
      "UNIDADES": "un",
      "COSTO": 8151,
      "COOR": 1.1,
      "FECHA_ACT": "2023-11",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189ad",
      "Nombre del producto": "Pelicula Alimento Chicle",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 200,
      "UNIDADES": "NaN",
      "COSTO": 13529,
      "COOR": 1.1,
      "FECHA_ACT": "2023-11",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189b2",
      "Nombre del producto": "Soda",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 12,
      "UNIDADES": "ml",
      "COSTO": 25100,
      "COOR": 1.1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189b7",
      "Nombre del producto": "TE NEGRO PRICE",
      "Proveedor": "Price Smart",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 3000,
      "UNIDADES": "gr",
      "COSTO": 30900,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189ba",
      "Nombre del producto": "COSTILLA",
      "Proveedor": "JE",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 980,
      "UNIDADES": "gr",
      "COSTO": 78000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189c0",
      "Nombre del producto": "PEZUNA",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 9000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189c2",
      "Nombre del producto": "POSTA",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 27000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189c3",
      "Nombre del producto": "PIERNA PULPA",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 18000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189c6",
      "Nombre del producto": "ESPINAZO",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 9000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189d1",
      "Nombre del producto": "Caramelo",
      "Proveedor": "INTERNO",
      "Estado": "50%",
      "Area": "CAFE_BEBIDAS",
      "category": "produccion_interna",
      "type": "items",
      "CANTIDAD": 600,
      "UNIDADES": "NaN",
      "COSTO": 19565.19,
      "COOR": 1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189d3",
      "Nombre del producto": "Cebolla caramelizada",
      "Proveedor": "INTERNO",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "produccion_interna",
      "type": "items",
      "CANTIDAD": 300,
      "UNIDADES": "NaN",
      "COSTO": 4736.75,
      "COOR": 1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189d4",
      "Nombre del producto": "Tomate Confi",
      "Proveedor": "INTERNO",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "produccion_interna",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "NaN",
      "COSTO": 40568.56,
      "COOR": 1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb1899b",
      "Nombre del producto": "TE CHAI",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 80,
      "UNIDADES": "gr",
      "COSTO": 36000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189a1",
      "Nombre del producto": "Caja Pizza Cuad 30x30x4",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 5,
      "UNIDADES": "un",
      "COSTO": 6302,
      "COOR": 1.1,
      "FECHA_ACT": "2023-11",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189ac",
      "Nombre del producto": "Film Stretch 15 cm",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 300,
      "UNIDADES": "NaN",
      "COSTO": 10756,
      "COOR": 1.1,
      "FECHA_ACT": "2023-11",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189ae",
      "Nombre del producto": "Seedpack Blonda 25,8",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 5,
      "UNIDADES": "un",
      "COSTO": 3529,
      "COOR": 1.1,
      "FECHA_ACT": "2023-11",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189af",
      "Nombre del producto": "Mezclador",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 500,
      "UNIDADES": "un",
      "COSTO": 6800,
      "COOR": 1.1,
      "FECHA_ACT": "2023-12",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189b4",
      "Nombre del producto": "Miga de galleta",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "NaN",
      "COSTO": 27700,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189b8",
      "Nombre del producto": "Frijol Verde desgranado",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": "NaN",
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189bf",
      "Nombre del producto": "TOCINO BARRIGUERO",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 22000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189c5",
      "Nombre del producto": "EMPELLA",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 6000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189c8",
      "Nombre del producto": "PIERNA ECONOMICA",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "gr",
      "COSTO": 16000,
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189c9",
      "Nombre del producto": "COSTILLA CERDO",
      "Proveedor": "La Vaquita",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "2155",
      "UNIDADES": "gr",
      "COSTO": "38597",
      "COOR": 1.05,
      "FECHA_ACT": "2024-08-23",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189cb",
      "Nombre del producto": "Clavo olor",
      "Proveedor": "La Vaquita",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": 10,
      "UNIDADES": "gr",
      "COSTO": 1850,
      "COOR": 1.05,
      "FECHA_ACT": "2024-07-08",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189d0",
      "Nombre del producto": "Hogao",
      "Proveedor": "INTERNO",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "produccion_interna",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "NaN",
      "COSTO": 9829.25,
      "COOR": 1,
      "FECHA_ACT": "2024-08-04",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189d2",
      "Nombre del producto": "Mermelada de Frutos Rojos",
      "Proveedor": "INTERNO",
      "Estado": "25%",
      "Area": "CAFE_BEBIDAS",
      "category": "produccion_interna",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "NaN",
      "COSTO": 17863.42,
      "COOR": 1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189d5",
      "Nombre del producto": "Pan ZhanYong",
      "Proveedor": "INTERNO",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "produccion_interna",
      "type": "items",
      "CANTIDAD": 533.3333333333334,
      "UNIDADES": "NaN",
      "COSTO": 5679.59,
      "COOR": 1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189d9",
      "Nombre del producto": "SIROPE DE CHAI",
      "Proveedor": "INTERNO",
      "Estado": "0%",
      "Area": "CAFE_BEBIDAS",
      "category": "produccion_interna",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "NaN",
      "COSTO": 166523.43,
      "COOR": 1,
      "FECHA_ACT": "2024-08-05",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189da",
      "Nombre del producto": "ESPUMA DE CAFE",
      "Proveedor": "INTERNO",
      "Estado": "75%",
      "Area": "CAFE_BEBIDAS",
      "category": "produccion_interna",
      "type": "items",
      "CANTIDAD": 245,
      "UNIDADES": "NaN",
      "COSTO": 6524.84,
      "COOR": 1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c6e75be722b9191cb189dc",
      "Nombre del producto": "JARABE FLOR DE JAMAICA",
      "Proveedor": "INTERNO",
      "Estado": "50%",
      "Area": "CAFE_BEBIDAS",
      "category": "produccion_interna",
      "type": "items",
      "CANTIDAD": 1000,
      "UNIDADES": "NaN",
      "COSTO": 25705.12,
      "COOR": 1,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da2f",
      "Nombre del producto": "Naranja",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da29",
      "Nombre del producto": "Jarabe Panela Naranja",
      "Proveedor": "NaN",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da30",
      "Nombre del producto": "Platano Maduro",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da35",
      "Nombre del producto": "Cemilla de Mostaza Negra",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da36",
      "Nombre del producto": "Cemilla de Mostaza Amarilla",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da37",
      "Nombre del producto": "Linaza",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da3d",
      "Nombre del producto": "Papaya",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da46",
      "Nombre del producto": "Samilla de Cilantro",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da48",
      "Nombre del producto": "Pimenton rojo",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da4c",
      "Nombre del producto": "Puerro Crocante",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da4d",
      "Nombre del producto": "Sriracha",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da54",
      "Nombre del producto": "Mayoneza",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da58",
      "Nombre del producto": "Mayo Picante",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da5b",
      "Nombre del producto": "Cebolla Encurtida",
      "Proveedor": "NaN",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da5d",
      "Nombre del producto": "Salsa Napolitana",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da2e",
      "Nombre del producto": "Mandarina",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da3a",
      "Nombre del producto": "Achiota",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da3c",
      "Nombre del producto": "Vinagre Blanco",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da3e",
      "Nombre del producto": "Zuccinni",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da42",
      "Nombre del producto": "Color",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da44",
      "Nombre del producto": "Sazon Completo",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da45",
      "Nombre del producto": "Crema de Mani",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da47",
      "Nombre del producto": "Oregano",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da49",
      "Nombre del producto": "Tomillo Molido",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da4e",
      "Nombre del producto": "Miel de abeja",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da53",
      "Nombre del producto": "Pie de manzan",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da5a",
      "Nombre del producto": "Hogao",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da5c",
      "Nombre del producto": "Cebolla Caramelizada",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da2b",
      "Nombre del producto": "Vasos 9oz",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da2d",
      "Nombre del producto": "Tomate riñon",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da31",
      "Nombre del producto": "Platano Verde",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da40",
      "Nombre del producto": "Curcuma",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da4f",
      "Nombre del producto": "Vinagre de frutas",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da52",
      "Nombre del producto": "Coliflor",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da55",
      "Nombre del producto": "Mermelada de Uchuva",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da59",
      "Nombre del producto": "Mayo Ajo",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da2a",
      "Nombre del producto": "Guandolo Piña",
      "Proveedor": "NaN",
      "Estado": "PENDIENTE",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da2c",
      "Nombre del producto": "Sandia",
      "Proveedor": "NaN",
      "Estado": "PENDIENTE",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da32",
      "Nombre del producto": "Calabacin",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da33",
      "Nombre del producto": "Pimienta Entera",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da34",
      "Nombre del producto": "Ajo en Polvo",
      "Proveedor": "NaN",
      "Estado": "PENDIENTE",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da38",
      "Nombre del producto": "Almendra",
      "Proveedor": "NaN",
      "Estado": "100%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da39",
      "Nombre del producto": "Paprika",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da3b",
      "Nombre del producto": "Laurel Hoja",
      "Proveedor": "NaN",
      "Estado": "75%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da3f",
      "Nombre del producto": "Chile Hojelas",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da41",
      "Nombre del producto": "Sal de Cebolla",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da43",
      "Nombre del producto": "Curry Mazala",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da4a",
      "Nombre del producto": "Laurel Molido",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da4b",
      "Nombre del producto": "Ajos en Aceite",
      "Proveedor": "NaN",
      "Estado": "25%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da50",
      "Nombre del producto": "Salsa de soya",
      "Proveedor": "NaN",
      "Estado": "50%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da51",
      "Nombre del producto": "Brocoli",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "COCINA",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da56",
      "Nombre del producto": "Mermelada de Frutos Rojos",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    },
    {
      "_id": "66c82603feaf7182c4c6da57",
      "Nombre del producto": "Mermelada de Frutos Amarillos",
      "Proveedor": "NaN",
      "Estado": "0%",
      "Area": "CAFE_BEBIDAS",
      "category": "compra_almacen",
      "type": "items",
      "CANTIDAD": "NaN",
      "UNIDADES": "NaN",
      "COSTO": "NaN",
      "COOR": 1.05,
      "FECHA_ACT": "NaN",
      "STOCK": "NaN",
      "GRUPO": "",
      "MARCA": ""
    }
  ]